version: '3'
services:
  chrome-instances:
    build: openvidu-client-puppeteer
    ports:
      - "4443"
      - "8443"
    command: "npm start"
    volumes:
      - ./logs/${SESSION_NAME}:/OpenVidu-Load-Testing-Puppeteer/logs
